Add Playwright and configuration file
NYCPlanning/ae-remix-template pull request #6
Opened 2024-03-11 16:21 UTC by bmarchena

Closes #5

2024-03-11 19:25 UTC, TangoYankee requested changes

2024-03-11 19:25 UTC, TangoYankee commented on package.json
> +    "test": "npx playwright test",
This seems to have displaced the ability to run vitest unit tests through an npm script

2024-03-11 20:01 UTC, bmarchena commented on package.json
> +    "test": "npx playwright test",
I've brought the script back and named it "vitest" but happy to rename again if we preferred it under "test"

2024-03-11 20:03 UTC, bmarchena commented on package.json
> +    "test": "npx playwright test",
I also had to add an `include` to the viteConfig so that the it wouldn't run the PlayWright tests so lmk if there are any misgivings regarding that

2024-03-12 18:45 UTC, TangoYankee commented on package.json
> +    "test": "npx playwright test",
[Filtering for vite tests on the "test" keyword](https://github.com/NYCPlanning/ae-remix-template/pull/6/files#diff-58e6f63d87181b1c6a8cb6e5f1691df04aa32854456efcd52ca71c8541375d26R18) does prevent us from using the "test" keyword in future playwright tests, lest they get swept up in the vitest runner.

But at this stage of development, I don't think we really know how we _do_ want to differentiate between playwright and vitest tests. The Zoning API still has a open discussion about how to structure its E2E and unit tests. I'll link this comment in that discussion to flag it as a consideration as part of that larger discussion.

For now, this meets the acceptance criteria. Squash the commits and I'll approve the PR.

2024-03-18 19:22 UTC, TangoYankee approved these changes

2024-03-21 16:25 UTC, merged